[mgr]
prepend_keymap = [
	{ on = [ "1" ], run = "plugin relative-motions 1", desc = "Relative motion" },
	{ on = [ "2" ], run = "plugin relative-motions 2", desc = "Relative motion" },
	{ on = [ "3" ], run = "plugin relative-motions 3", desc = "Relative motion" },
	{ on = [ "4" ], run = "plugin relative-motions 4", desc = "Relative motion" },
	{ on = [ "5" ], run = "plugin relative-motions 5", desc = "Relative motion" },
	{ on = [ "6" ], run = "plugin relative-motions 6", desc = "Relative motion" },
	{ on = [ "7" ], run = "plugin relative-motions 7", desc = "Relative motion" },
	{ on = [ "8" ], run = "plugin relative-motions 8", desc = "Relative motion" },
	{ on = [ "9" ], run = "plugin relative-motions 9", desc = "Relative motion" },
	{ on = [ "m" ], run = "plugin relative-motions", desc = "Start relative motion" },
	{ on = [ "g", "." ], run = "hidden toggle", desc = "Toggle hidden files" },
	{ on = [ "g", "m" ], run = "linemode size_and_mtime", desc = "Linemode: size + mtime" },
	{ on = [ "g", "s" ], run = "linemode size", desc = "Linemode: size" },
	{ on = [ "g", "t" ], run = "linemode mtime", desc = "Linemode: mtime" },
	{ on = [ "g", "p" ], run = "cd ~/.config", desc = "Cd to ~/.config" },
	{ on = [ "g", "h" ], run = "cd ~", desc = "Cd to home" },
	{ on = [ "g", "r" ], run = "cd /", desc = "Cd to root" },
	{ on = [ "g", "n" ], run = "sort natural --dir-first", desc = "Sort naturally" },
	{ on = [ "g", "e" ], run = "sort mtime --reverse --dir-first", desc = "Sort by newest" },
	{ on = [ "g", "z" ], run = "sort size --reverse --dir-first", desc = "Sort by largest" },
	{ on = [ "o", "r" ], run = "open --interactive", desc = "Open with..." },
	{ on = [ "c", "p" ], run = "copy path", desc = "Copy file path" },
	{ on = [ "c", "f" ], run = "copy filename", desc = "Copy filename" },
	{ on = [ "c", "d" ], run = "copy dirname", desc = "Copy parent dir" },
]
